CREATE TABLE `llm_connections` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text DEFAULT 'local' NOT NULL,
	`kind` text NOT NULL,
	`sdk` text NOT NULL,
	`catalog_provider_id` text,
	`label` text NOT NULL,
	`base_url` text,
	`auth_type` text NOT NULL,
	`account_label` text,
	`account_id` text,
	`key_hint` text,
	`token_expires_at` text,
	`refresh_lock_until` text,
	`google_project` text,
	`google_client_id` text,
	`selections` text NOT NULL,
	`models_cache` text,
	`models_fetched_at` text,
	`models_error` text,
	`status` text DEFAULT 'untested' NOT NULL,
	`last_error` text,
	`last_tested_at` text,
	`concurrency` integer DEFAULT 2 NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
