// One-time local setup: env file, browser for PDF rendering and applying, database.
import { execSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";

const run = (cmd) => {
  console.log(`\n> ${cmd}`);
  execSync(cmd, { stdio: "inherit" });
};

function ensureWorkerToken() {
  const envPath = ".env";
  if (!fs.existsSync(envPath)) {
    fs.copyFileSync(".env.example", envPath);
    console.log("Created .env from .env.example. Add your AI provider credentials there.");
  }
  let env = fs.readFileSync(envPath, "utf8");
  const token = crypto.randomBytes(32).toString("hex");
  if (!/^PROWL_WORKER_TOKEN=/m.test(env)) {
    env = `${env.replace(/\s*$/, "")}\n\n# Shared secret for the worker control API (generated by pnpm bootstrap)\nPROWL_WORKER_TOKEN=${token}\n`;
    fs.writeFileSync(envPath, env);
    console.log("Generated PROWL_WORKER_TOKEN in .env (web → worker control API).");
  } else if (/^PROWL_WORKER_TOKEN=\s*$/m.test(env)) {
    env = env.replace(/^PROWL_WORKER_TOKEN=\s*$/m, `PROWL_WORKER_TOKEN=${token}`);
    fs.writeFileSync(envPath, env);
    console.log("Generated PROWL_WORKER_TOKEN in .env (web → worker control API).");
  }
}

ensureWorkerToken();
run("pnpm --filter @prowl/documents exec playwright install chromium");
run("pnpm db:migrate");
console.log("\nSetup complete. Start everything with: pnpm dev  (then open http://localhost:3000)");
